/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface HelloSmartContractInterface extends utils.Interface {
  functions: {
    "retrieveWord()": FunctionFragment;
    "setWord(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "retrieveWord" | "setWord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "retrieveWord",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWord",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "retrieveWord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWord", data: BytesLike): Result;

  events: {};
}

export interface HelloSmartContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HelloSmartContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    retrieveWord(overrides?: CallOverrides): Promise<[string]>;

    setWord(
      _word: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  retrieveWord(overrides?: CallOverrides): Promise<string>;

  setWord(
    _word: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    retrieveWord(overrides?: CallOverrides): Promise<string>;

    setWord(
      _word: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    retrieveWord(overrides?: CallOverrides): Promise<BigNumber>;

    setWord(
      _word: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    retrieveWord(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setWord(
      _word: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
